ETC Course Intro: Update index.md
ethereumclassic/ethereumclassic.github.io pull request #1036
Opened 2022-12-15 14:12 UTC by DonaldMcIntyre

Fixed grammar/typos suggested by @TheCrowbill.

2022-12-15 15:42 UTC, cyberus7569 requested changes
Donald! looks good. I hate to be that person... but we should go ahead and remove the **and** in the section "in general, **and** it is divided in several sections" and capitalize the "It" that follows <3

2022-12-15 21:47 UTC, w1g0 approved these changes

2022-12-18 06:07 UTC, TheCrowbill requested changes

2022-12-18 06:07 UTC, TheCrowbill commented on content/blog/2022-12-15-introduction-to-the-ethereum-classic-course/index.md
> +As seen in this introduction, the Ethereum Classic course promises to be a thorough educational experience about ETC and the industry in general, and it is divided in several sections with small unit
```suggestion
As seen in this introduction, the Ethereum Classic course promises to be a thorough educational experience about ETC and the industry in general. It is divided into several sections with small units so they are easier to process and comprehend.
```
The current revision is a comma-spliced run-on sentence; a "no-no" in written English.

2022-12-18 21:51 UTC, w1g0 approved these changes

2022-12-20 18:18 UTC, TheCrowbill approved these changes

2022-12-20 19:55 UTC, merged