ETC Course: 3. The First Digital Currency Attempts
ethereumclassic/ethereumclassic.github.io pull request #1043
Opened 2022-12-22 01:56 UTC by DonaldMcIntyre

This is class 3 of the ETC course.

Chinese translation soon.

This will be published on 2023-01-05.

2023-01-03 02:20 UTC, gitr0n1n submitted a review, later dismissed

2023-01-03 15:35 UTC, w1g0 approved these changes

2023-01-03 21:36 UTC, TheCrowbill requested changes
Line 77: Corrected verb tense.
Line 77: Separated comma-spliced sentence.

2023-01-03 21:36 UTC, TheCrowbill commented on content/blog/2023-01-05-ethereum-classic-course-3-the-first-digital-currency-attempts/index.md
> +What Satoshi Nakamoto did was to integrated all these pioneering ideas into Bitcoin, and then Ethereum Classic adopted the majority of Bitcoin’s model for its base security.
```suggestion
What Satoshi Nakamoto did was to integrate all these pioneering ideas into Bitcoin, and then Ethereum Classic adopted the majority of Bitcoin’s model for its base security. 
```

2023-01-03 21:36 UTC, TheCrowbill commented on content/blog/2023-01-05-ethereum-classic-course-3-the-first-digital-currency-attempts/index.md
> +What Satoshi Nakamoto did was to integrated all these pioneering ideas into Bitcoin, and then Ethereum Classic adopted the majority of Bitcoin’s model for its base security.
```suggestion
What Satoshi Nakamoto did was to integrate all these pioneering ideas into Bitcoin. Ethereum Classic then adopted the majority of Bitcoin’s model for its base security. 
```

2023-01-03 23:37 UTC, TheCrowbill approved these changes

2023-01-04 00:02 UTC, gitr0n1n approved these changes

2023-01-05 12:57 UTC, merged