Alert: Endpoints Migration From Ethercluster to Rivet
ethereumclassic/ethereumclassic.github.io pull request #1058
Opened 2023-01-03 22:05 UTC by DonaldMcIntyre

This is an alert for all the ecosystem to migrate from Ethercluster to Rivet as announced by the ETC Cooperative.

It is for 2023-01-04.

2023-01-04 00:10 UTC, gitr0n1n commented
A draft, not ready for review with less than 24 hours as a post date?

@DonaldMcIntyre please provide longer review times for these articles. I see six incomplete drafts and one PR ready for review. All with pressing dates.

Please finish these PRs and then schedule posting dates. You're putting reviewers in a rushed situation with this current approach. Thanks in advance. We shouldn't feel a need to check more than once a week imo.

Not a big deal and not negative, we just need to iron out these work flow issues. 👍

2023-01-04 01:33 UTC, DonaldMcIntyre commented
> A draft, not ready for review with less than 24 hours as a post date?
> 
> @DonaldMcIntyre please provide longer review times for these articles. I see six incomplete drafts and one PR ready for review. All with pressing dates.
> 
> Please finish these PRs and then schedule posting dates. You're putting reviewers in a rushed situation with this current approach. Thanks in advance. We shouldn't feel a need to check more than once a week imo.
> 
> Not a big deal and not negative, we just need to iron out these work flow issues. 👍

Thank you Ronin, sorry for this one, it was a last minute addition to replace the one that we dropped for tomorrow.

In November and December the flow went well, I think these days it's slow to review because of the holidays and people are getting back to work on these things. Nevertheless, we have to provide the PRs for review several days in advance not in the last minute. 

Mind that the 6 that are pending are for all of January, they are not all urgent. The key is to have the Chinese translation as soon as possible so the PR is out of draft and ready for review many days in advance.

Also, the flow is only 3 articles per week, it doesn't seem too much for several admins to process. Again, sorry for this one in particular which was, indeed, a last minute addition. We can just wait until admins have time to process it.

2023-01-04 11:51 UTC, w1g0 requested changes
The Rivet Discord invite link is invalid for the English version as well as for the Chinese version.

2023-01-04 14:11 UTC, w1g0 submitted a review, later dismissed

2023-01-04 17:38 UTC, bobsummerwill requested changes
I think this article needs toning down to just expressing the basic facts, and referring back to the article on the ETC Coop site.

It is inappropriate, for example, to have the "sell" from Rivet here or about Coop's history of providing this service, IMHO.

There are other people providing endpoints too.

2023-01-04 17:48 UTC, w1g0 commented
> I think this article needs toning down to just expressing the basic facts, and referring back to the article on the ETC Coop site.
> 
> It is inappropriate, for example, to have the "sell" from Rivet here or about Coop's history of providing this service, IMHO.
> 
> There are other people providing endpoints too.

The article is clearly addressed to people that currently are using EtherCluster to migrate to Rivet, so I see no issue there but I understand your POV and am fine with it either way.

2023-01-04 18:20 UTC, bobsummerwill commented
We should have no need to rush this one.

The transition is happening over the next 6 months+

2023-01-04 19:17 UTC, DonaldMcIntyre commented
> I think this article needs toning down to just expressing the basic facts, and referring back to the article on the ETC Coop site.
> 
> It is inappropriate, for example, to have the "sell" from Rivet here or about Coop's history of providing this service, IMHO.
> 
> There are other people providing endpoints too.

I will trim the ETC Coop's and Rivet's sell segments and refer to the Coop's original post, but I will leave the sense of urgency to make the migration and the datapoints of the endpoints.

Will change it today.

cc @w1g0

2023-01-04 23:09 UTC, DonaldMcIntyre commented
@w1g0 @bobsummerwill  Changes done! It would be great if you could approve it so we publish it, thank you!

2023-01-04 23:29 UTC, bobsummerwill requested changes

2023-01-04 23:29 UTC, bobsummerwill commented on content/blog/2023-01-04-alert-migrate-your-etc-endpoints-from-ethercluster-to-rivet-by-july-1st-2023/index.md
> +## Summary
I think you can omit the Summary section at the end.  It is redundant, especially with the article now being so short.
Just keep the WARNING AT THE END, but not the Summary heading or body.

Also worth saying that alternative endpoints are also available.   See /network/endpoints/ for more details.

2023-01-05 04:16 UTC, TheCrowbill approved these changes
After the requested changes, LGTM.

2023-01-05 04:16 UTC, TheCrowbill commented on content/blog/2023-01-04-alert-migrate-your-etc-endpoints-from-ethercluster-to-rivet-by-july-1st-2023/index.md
> +The last day for the current Ethercluster rpc endpoint is July 1st of 2023.
```suggestion
The last day for the current Ethercluster RPC endpoint is July 1st of 2023.
```

2023-01-05 15:06 UTC, bobsummerwill reviewed
English text looks good.
We need to wait on the Chinese translation, and then I am good to merge.

2023-01-06 02:54 UTC, TheCrowbill approved these changes

2023-01-06 03:32 UTC, DonaldMcIntyre commented
> English text looks good. We need to wait on the Chinese translation, and then I am good to merge.

Chinese version is updated.

2023-01-06 18:04 UTC, bobsummerwill approved these changes
LTGM, but please do remember to squash the commits on merge.  Messy history with all the iteration.  Thanks!

2023-01-06 18:19 UTC, merged

2023-01-06 18:20 UTC, DonaldMcIntyre commented
> LTGM, but please do remember to squash the commits on merge.  Messy history with all the iteration.  Thanks!

Squished and merged, thank you!