ETC Course: 7. ETC's Philosophy of Code I Law
ethereumclassic/ethereumclassic.github.io pull request #1071
Opened 2023-01-19 23:53 UTC by DonaldMcIntyre

This is class 7 of the ETC course that explain what is code is law and where it come from.

Chinese translation coming soon.

It will be published on 2023-02-02.

As the course is a systematic system of teaching everything about ETC, it may have some overlapping topics with single articles and videos. But, this is fine as it increases the search surface of ETC topics and the themes appear in different settings (e.g. in a structured course and in unstructured single articles and videos).

2023-01-27 19:41 UTC, brolal approved these changes

2023-01-31 08:10 UTC, TheCrowbill requested changes

2023-01-31 08:10 UTC, TheCrowbill commented on content/blog/2023-02-02-ethereum-classsic-course-7-ethereum-classics-philosophy-of-code-is-law/index.md
> +So, code is law on the blockchain. All executions are final, all transactions are immutable. For everything else, there is a time-tested way to adjudicate legal disputes and carry out the administrat
Line 88: Bracketing implied words
```suggestion
So, code is law on the blockchain. All executions are final, all transactions are immutable. For everything else, there is a time-tested way to adjudicate legal disputes and carry out the administration of justice. It’s called [the] legal system.”
```

2023-01-31 17:07 UTC, TheCrowbill approved these changes

2023-01-31 18:38 UTC, brolal approved these changes

2023-02-02 12:54 UTC, merged