What Does Security Mean in ETC
ethereumclassic/ethereumclassic.github.io pull request #1082
Opened 2023-02-03 00:36 UTC by DonaldMcIntyre

This is an opinion post about the meaning of security in ETC.

Chinese translation soon.

It will be published on Feb 15th.

2023-02-09 17:41 UTC, brolal submitted a review, later dismissed

2023-02-13 03:03 UTC, TheCrowbill requested changes

2023-02-13 03:03 UTC, TheCrowbill commented on content/blog/2023-02-15-what-does-security-mean-in-ethereum-classic/index.md
> +However, when it comes to authorized theft; the arbitrary over taxation, confiscation, censorship, limitation, or elimination of people's Life, Liberty and Property by tyrannical law; then proof of s
Line 57: Correct punctuation; Add hyphen; Add comma; Rewrite for clarity
```suggestion
However, when it comes to authorized theft, the arbitrary over-taxation, confiscation, censorship, limitation, or elimination of people's Life, Liberty, and Property by tyrannical law, then proof of stake advocates are either absolutely compliant or totally in favor of such situations.
```

2023-02-13 16:10 UTC, TheCrowbill reviewed
LGTM

2023-02-13 16:10 UTC, TheCrowbill approved these changes

2023-02-14 02:16 UTC, gitr0n1n approved these changes
@DonaldMcIntyre make sure your YouTube video link works. It did not work during my review.

2023-02-15 13:04 UTC, DonaldMcIntyre commented
> @DonaldMcIntyre make sure your YouTube video link works. It did not work during my review.

Thank you. The video is in private mode. Yes, I move it to public when I publish it. Thanks!

2023-02-15 13:04 UTC, merged