How to Contribute to ETC: Community Volunteering
ethereumclassic/ethereumclassic.github.io pull request #1126
Opened 2023-03-08 02:20 UTC by DonaldMcIntyre

This is part of the series "How to Contribute to ETC", and this one is about volunteering.

Chinese version done.

This one will be published on 2023-03-21.

2023-03-20 18:37 UTC, TheCrowbill requested changes
Changes requested, although most are simply suggestions

2023-03-20 18:37 UTC, TheCrowbill commented on content/blog/2023-03-21-how-to-contribute-to-etc-community-volunteering/index.md
> +
Line 130: Addition
```suggestion

For more details on how to contribute items for inclusion on the ETC website see an earlier article from this series entitled ["How to Contribute to ETC: The Community Website"](https://www.ethereumclassic.org/blog/2023-01-03-how-to-contribute-to-etc-community-website).

```

2023-03-20 18:37 UTC, TheCrowbill commented on content/blog/2023-03-21-how-to-contribute-to-etc-community-volunteering/index.md
> +One of the most valuable ways of volunteering for ETC is by using your talents and knowledge to advance the network. There are many contributors who do research, write, and produce videos regularly f
Line 135: Revise word order; Correct usage
```suggestion
One of the most valuable ways of volunteering for ETC is by using your talents and knowledge to advance the network. There are many contributors who regularly do research, write, and produce videos about Ethereum Classic.
```

2023-03-20 18:37 UTC, TheCrowbill commented on content/blog/2023-03-21-how-to-contribute-to-etc-community-volunteering/index.md
> +- Etherplan: https://etherplan.com
Line 139: Embed link
```suggestion
- [Etherplan](https://etherplan.com)
```

2023-03-20 18:37 UTC, TheCrowbill commented on content/blog/2023-03-21-how-to-contribute-to-etc-community-volunteering/index.md
> +- PatientMoney: https://www.youtube.com/@PatientMoney
Line 140: Embed link
```suggestion
- [PatientMoney](https://www.youtube.com/@PatientMoney)
```

2023-03-20 18:37 UTC, TheCrowbill commented on content/blog/2023-03-21-how-to-contribute-to-etc-community-volunteering/index.md
> +- SavageProfits: https://www.youtube.com/@SavageProfits
Line 141: Embed link
```suggestion
- [SavageProfits](https://www.youtube.com/@SavageProfits)
```

2023-03-20 18:37 UTC, TheCrowbill commented on content/blog/2023-03-21-how-to-contribute-to-etc-community-volunteering/index.md
> +- StonkInsights: https://www.youtube.com/@stonkinsights
Line 142: Embed link
```suggestion
- [StonkInsights](https://www.youtube.com/@stonkinsights)
```

2023-03-20 18:37 UTC, TheCrowbill commented on content/blog/2023-03-21-how-to-contribute-to-etc-community-volunteering/index.md
> +- Ethereum Classic Updates: https://www.youtube.com/@ETCupdates
Line 143: Embed link
```suggestion
- [Ethereum Classic Updates](https://www.youtube.com/@ETCupdates)
```

2023-03-21 04:33 UTC, TheCrowbill requested changes

2023-03-21 04:33 UTC, TheCrowbill commented on content/blog/2023-03-21-how-to-contribute-to-etc-community-volunteering/index.md
> +![ECIP editors.](./3.png)
Liine 68: Move graphic to ECIP section
```suggestion
```

2023-03-21 04:33 UTC, TheCrowbill commented on content/blog/2023-03-21-how-to-contribute-to-etc-community-volunteering/index.md
> +As ETC is an open source project, any changes to its protocol or software must go through a public process called the Ethereum Classic Improvement Proposal (ECIP) process.
Line 98: Insert graphic
```suggestion
![ECIP editors.](./3.png)

As ETC is an open source project, any changes to its protocol or software must go through a public process called the Ethereum Classic Improvement Proposal (ECIP) process.
```

2023-03-21 22:36 UTC, gitr0n1n approved these changes

2023-03-22 17:53 UTC, brolal approved these changes

2023-03-22 17:57 UTC, chris-mercer approved these changes

2023-03-22 18:21 UTC, merged