ETC Migrates to POS, Sharding, Cancels Supply Cap
ethereumclassic/ethereumclassic.github.io pull request #1145
Opened 2023-03-20 21:16 UTC by DonaldMcIntyre

This is for April 1st. No Chinese version. It is an explanation of the most important changes ETC will undergo in its history. 🚀

2023-03-21 03:02 UTC, gitr0n1n commented
i hate these.

2023-03-21 03:03 UTC, gitr0n1n submitted a review, later dismissed

2023-03-21 04:53 UTC, TheCrowbill requested changes

2023-03-21 04:53 UTC, TheCrowbill commented on content/blog/2023-04-01-etc-is-migrating-to-pos-sharding-its-blockchain-and-lifting-its-supply-cap/index.md
> +After the nerve wrecking days of the recent financial crisis, the ETC community has come to the realization that a fixed supply and an algorithmic monetary policy is not only evil but one of the wors
Line 32: Correct spelling; Correct usage; Correct pronoun usage; Correct subject-verb agreement; Edit for agreement
```suggestion
After the nerve-wracking days of the recent financial crisis, the ETC community has come to the realization that a fixed supply and an algorithmic monetary policy are not only evil but are among the worst ways to protect people's property on a global scale. The best method is to be able to print money whenever the community deems it necessary, bringing four solutions to the world at the same time, with no cost whatsoever to ETC constituents:
```

2023-03-21 05:00 UTC, TheCrowbill submitted a review, later dismissed
I have marked grammar revisions on one line.

PR is approved for merging to prevent needing repeated revision reviews.

2023-03-21 12:12 UTC, DonaldMcIntyre commented
> I have marked grammar revisions on one line.
> 
> PR is approved for merging to prevent needing repeated revision reviews.

Oh, I accepted the commits, so it needs new approvals. Sorry, I hadn't read this, or I don't know how to deal with this.

2023-03-21 12:14 UTC, DonaldMcIntyre commented
> i hate these.

We can just delete it. An April Fools article was requested by @brolal, so I just wrote this one. If it is not found appropriate or that it may confuse people, we can just discard it.

2023-03-21 16:58 UTC, brolal commented on content/blog/2023-04-01-etc-is-migrating-to-pos-sharding-its-blockchain-and-lifting-its-supply-cap/index.md
> +Brotherlal, another prominent community member said "this has been written on the wall all this time and ETC is blessed to have finally opened its eyes to the future of #DEFI, #TradFI, #LegFI, #GovFI
" at the end :))

2023-03-21 19:48 UTC, DonaldMcIntyre commented
> > > We can just delete it. An April Fools article was requested by @brolal, so I just wrote this one.
> > > If it is not found appropriate or that it may confuse people, we can just discard it.
> 
> Yeah - it might be best to skip this actually.

Closing it.

2023-03-21 19:49 UTC, closed without merging

2023-03-21 23:39 UTC, gitr0n1n commented
> > i hate these.
> 
> We can just delete it. An April Fools article was requested by @brolal, so I just wrote this one. If it is not found appropriate or that it may confuse people, we can just discard it.

You don't have to close because I hate them. But I do hate them due to the confusion they bring. Its and industry thing, so by all means go ahead. I approved, but just vocalized my personal opinion that I dislike them due to the misinformation they bring to plebs.

2023-03-22 01:12 UTC, DonaldMcIntyre commented
> > > i hate these.
> > 
> > 
> > We can just delete it. An April Fools article was requested by @brolal, so I just wrote this one. If it is not found appropriate or that it may confuse people, we can just discard it.
> 
> You don't have to close because I hate them. But I do hate them due to the confusion they bring. Its an industry thing, so by all means go ahead. I approved, but just vocalized my personal opinion that I dislike them due to the misinformation they bring to plebs.

I deleted it because Bob also didn't like it so let's just close it. Thank you!