The Meaning of Finality in ETC
ethereumclassic/ethereumclassic.github.io pull request #1171
Opened 2023-04-12 00:46 UTC by DonaldMcIntyre

This is a post and video that explains why the finality of ETC PoW is better than just legal or proof of stake finality. It explains finality from different perspectives and distinguishes physical finality (PoW) from legal finality and social consensus finality as in ETH. It also talks about other details.

EN.

CN version done.

This one will be published on April 25 of 2023. We have a 14 day lead.

2023-04-24 22:00 UTC, TheCrowbill requested changes
> Contrary to what proof of stake advocates say, humans, whether lawyers or computer scientists, are not good sources of finality. 

Love this!

2023-04-24 23:48 UTC, TheCrowbill requested changes
Corrected line 52 suggestion

2023-04-25 00:44 UTC, TheCrowbill approved these changes

2023-04-25 05:22 UTC, brolal approved these changes

2023-04-25 11:55 UTC, merged