ETC Course: 20. Custodial vs Non-custodial Wallets
ethereumclassic/ethereumclassic.github.io pull request #1187
Opened 2023-04-21 00:40 UTC by DonaldMcIntyre

This is class 20 of the ETC course that explains what are custodial ad non-custodial wallets. In the next two classes we will explain what are cold and hot wallets, and hardware and software wallets.

EN.

CN coming soon.

This one will be posted on 2023-05-04. WE have a 14 day lead.

2023-05-04 04:42 UTC, brolal submitted a review, later dismissed

2023-05-05 00:53 UTC, TheCrowbill requested changes

2023-05-05 00:53 UTC, TheCrowbill commented on content/blog/2023-05-04-ethereum-classic-course-20-what-are-custodial-and-non-custodial-wallets/index.md
> +The wallet apps that let your generate your own private keys and store them in various forms are called non-custodial wallets.
Line 71: Correct spelling typo
```suggestion
The wallet apps that let you generate your own private keys and store them in various forms are called non-custodial wallets.
```

2023-05-05 05:15 UTC, TheCrowbill approved these changes

2023-05-09 05:10 UTC, brolal approved these changes

2023-05-09 13:20 UTC, merged