ETC Course: 22. What Are Hot and Cold Wallets?
ethereumclassic/ethereumclassic.github.io pull request #1200
Opened 2023-05-05 03:32 UTC by DonaldMcIntyre

This is class 22 of the ETC course that explains what are hot and cold wallets.

EN.

CN coming soon.

This one will be published on 2023-05-18, so we have a 14 day lead.

2023-05-16 23:04 UTC, TheCrowbill requested changes

2023-05-16 23:04 UTC, TheCrowbill commented on content/blog/2023-05-18-ethereum-classic-course-22-what-are-hot-and-cold-wallets/index.md
> +This means that a typical cold wallet is and address where you only received crypto and hardly ever send any.
Line 49: Fix typo; Add quantifier
```suggestion
This means that a typical cold wallet is an address where you only receive crypto and hardly, if ever, send any.
```

2023-05-17 05:50 UTC, brolal approved these changes

2023-05-17 21:49 UTC, TheCrowbill approved these changes

2023-05-18 11:55 UTC, merged