The Newly Redesigned Ethereum Classic Multisig
ethereumclassic/ethereumclassic.github.io pull request #1235
Opened 2023-06-06 03:59 UTC by DonaldMcIntyre

This post presents the newly redesigned Ethereum Classic multisig wallet and shows how to create a new Safe wallet from scratch using the new interface. We also announce that it was renamed to Ethereum Classic Multisig.

"Using the Newly Redesigned Ethereum Classic Multisig Wallet"

EN.

CN coming soon.

This one will be published on 2023-06-19. We have a 14 day lead.

2023-06-18 14:54 UTC, TheCrowbill requested changes

2023-06-18 14:54 UTC, TheCrowbill commented on content/blog/2023-06-19-using-the-newly-redesigned-ethereum-classic-multisig-wallet/index.md
> +Finally, you need to set the threshold of how many signatures are needed to sign transactions in this multisig wallet. For example, you may chose, 1 of 3, 2 of 3, or 3 of 3.
Line 107: Correct spelling
```suggestion
Finally, you need to set the threshold of how many signatures are needed to sign transactions in this multisig wallet. For example, you may choose, 1 of 3, 2 of 3, or 3 of 3. 
```

2023-06-19 03:02 UTC, TheCrowbill approved these changes
LG

2023-06-19 04:53 UTC, brolal approved these changes

2023-06-19 11:59 UTC, merged