ETC Course: 28. What Are Privacy Coins?
ethereumclassic/ethereumclassic.github.io pull request #1246
Opened 2023-06-17 01:59 UTC by DonaldMcIntyre

This is class 28 of the ETC course that explains what are privacy coins. It includes a ranking of the top ten and information about market caps.

"Ethereum Classic Course: 28. What Are Privacy Coins?"

EN.

CN coming soon.

This one will be published on June 29 2023 so we have a 13 day lead.

2023-06-27 20:28 UTC, TheCrowbill requested changes

2023-06-27 20:28 UTC, TheCrowbill commented on content/blog/2023-06-29-ethereum-classic-course-28-what-are-privacy-coins/index.md
> +In the context described above, and to enhance individual user security, privacy coins have made the tradeoff of reducing transparency of their systems to increase the secrecy of transactions, addres
Liner 38: Rewrite for readability
```suggestion
In the above context, and in order to enhance the security of individual users, privacy coins have made the tradeoff of reducing the transparency of their systems in order to increase the secrecy of transactions, addresses, and balances.
```

2023-06-27 20:28 UTC, TheCrowbill commented on content/blog/2023-06-29-ethereum-classic-course-28-what-are-privacy-coins/index.md
> +On Zcash users may opt to send private or transparent transactions.
Line 56: Added comma
```suggestion
On Zcash, users may opt to send private or transparent transactions.
```

2023-06-27 20:28 UTC, TheCrowbill commented on content/blog/2023-06-29-ethereum-classic-course-28-what-are-privacy-coins/index.md
> +In the image in this section you may see the top ten privacy coins on CoinMarketCap.
Line 62: Rewrite for readability
```suggestion
The accompanying image shows the top ten privacy coins listed on CoinMarketCap.
```

2023-06-27 20:28 UTC, TheCrowbill commented on content/blog/2023-06-29-ethereum-classic-course-28-what-are-privacy-coins/index.md
> +A general risk for these coins, that is usually pointed out, is that the transparency of the traditional blockchains makes them easy to audit and reveal bugs or flaws that can subsequently be fixed,
Line 86:  Rewrite for readability
```suggestion
A commonly known general risk for privacy coins is that the transparency of the traditional blockchains makes them easy to audit, revealing bugs or flaws that can subsequently be fixed, but if privacy coins hide all or part of that information, it becomes impossible to audit the design, function, monetary supply, or other key metrics of the blockchain.
```

2023-06-28 06:39 UTC, TheCrowbill approved these changes
LG

2023-06-29 04:40 UTC, brolal approved these changes

2023-06-29 11:54 UTC, merged