ETC Ecosystem Spotlight: HebeSwap Part I
ethereumclassic/ethereumclassic.github.io pull request #1252
Opened 2023-06-19 00:21 UTC by DonaldMcIntyre

This is part I of a two part series that will explain what is HebeBlock and HebeSwap. It explains some of their products, the HEBE token, several other things the team does, and leaves for part II the guide of how to trade on HebeSwap.

"ETC Ecosystem Spotlight: HebeSwap Part I"

EN.

CN done.

This post will be published on June 20th 2023. Please approve.

2023-06-19 01:13 UTC, TheCrowbill requested changes

2023-06-19 01:13 UTC, TheCrowbill commented on content/blog/2023-06-20-etc-ecosystem-spotlight-hebeswap-part-I/index.md
> +The way it works, is that users may deposit cryptocurrencies into the liquidity pools in the proportions of the market price for each pair. Then, when traders pay commissions when they buy and sell t
Line 79: Remove unneeded comma; Reword for readability
```suggestion
The way it works is that users may deposit cryptocurrencies into the liquidity pools in the proportions of the market price for each pair. Then, when traders pay commissions as they buy and sell these pairs, part of the commissions is paid as interest to the liquidity providers.
```

2023-06-19 03:05 UTC, TheCrowbill approved these changes
LG 👍

2023-06-19 04:51 UTC, brolal approved these changes

2023-06-19 17:42 UTC, gitr0n1n requested changes
Please address comments before merging.

2023-06-19 17:42 UTC, gitr0n1n commented on content/blog/2023-06-20-etc-ecosystem-spotlight-hebeswap-part-I/index.md
"it is growing organically and is a fundamental piece of infrastructure for the ecosystem"

- This product ran an ICO for 6,000 ETC if I remember correctly. This was not organic growth.

2023-06-19 17:42 UTC, gitr0n1n commented on content/blog/2023-06-20-etc-ecosystem-spotlight-hebeswap-part-I/index.md
"The HebeBlock team projects that they will be launching a DAO so the community may vote on development, upgrades, and compensation issues.

They estimate that when the token rises in value as the ecosystem grows, that the monthly issuance may be significantly reduced. For this they will have the DAO setup for the community to vote on these issues."
- @DonaldMcIntyre as you know, this isn't good lingo to have around as the SEC is hammering ICO's for being unregistered securities extracting funding from US participants. Especially as CEX's are delisting projects with these liabilities attached to them.

Also on the point of violating regulations and the legal liabilities that follow a project; let's also not forget Hebe's "gateway.hebeswap.com" which was a non-kyc centralized bridge that opened their team up to FinCEN regulation violations. Outside of it being a very dumb idea of taking in stablecoin form the public, buying BUSD on Binance, then calling it USDT on Ethereum Classic's network.

2023-06-19 18:26 UTC, merged

2023-06-19 18:27 UTC, gitr0n1n commented
@ethereumclassic/website might want to make sure @DonaldMcIntyre doesn't go rouge like we've seen with other ETC Coop employees (stev).

2023-07-07 01:47 UTC, gitr0n1n commented
@ethereumclassic/website  Note, 2 weeks later this bridge is materially compromised again. https://twitter.com/multichainorg/status/1677096839731097600

![image](https://github.com/ethereumclassic/ethereumclassic.github.io/assets/58588775/10c90379-7bd7-4787-87bb-994ed69ab7fe)


>"All the external tokens, meaning the tokens that are not issued inside ETC but exist in other chains, are bridged into the Ethereum Classic network through a technology called Multichain."

>Please note as the team that organized the Multichain bridge (Ethereum Classic DAO/EthereumClassic.com project/ETCswap). We advised people to pull their liquidity from that bridging due to centralization risk back in November 2022. In May 2023, their CEO went missing and the product appears to be in trouble given the lack of KYC and exposed centralized custody of user assets. This is why over $200K of liquidity left ETCswap in November 2022. I would view Multichain bridge as "deprecated" at this moment and it seems unwise you promote users putting more liqudity into that cross-chain routing protocol. @IstoraMandiri and I are on calls talking about this when our team organized that bridge. Then I've been on numerous community calls alerting to that centralized risk of losing your bridged assets.

https://github.com/ethereumclassic/ethereumclassic.github.io/pull/1252#discussion_r1234312508

2023-07-07 05:59 UTC, gitr0n1n commented
Well it happened ~20 days after this warning. The bridged assets are stuck. @ethereumclassic/website you allowed Donald to throw a tantrum and get his way at the expense of the ETC community. The warning was clear as day and instead he used social engineering and exploited his roles in this repo to push this content despite valid and provable concerns on the content of this post. A good point to reflect on how this was handled.

![image](https://github.com/ethereumclassic/ethereumclassic.github.io/assets/58588775/8658a4c3-b6cf-4fe7-abf9-ef2286bb5f43)

https://twitter.com/MultichainOrg/status/1677180114227056641