Add contribution info to readme
ethereumclassic/ethereumclassic.github.io pull request #1255
Opened 2023-06-19 06:52 UTC by IstoraMandiri

2023-06-19 14:56 UTC, TheCrowbill requested changes

2023-06-19 14:56 UTC, TheCrowbill commented on README.md
> +If you want submit content or make updates to ethereumclassic.org, you can do so in a number of ways:
Line 13: Add missing preposition
```suggestion
If you want to submit content or make updates to ethereumclassic.org, you can do so in a number of ways:
```

2023-06-19 18:46 UTC, DonaldMcIntyre approved these changes

2023-06-20 06:46 UTC, TheCrowbill approved these changes
LG

2023-06-22 03:09 UTC, DonaldMcIntyre approved these changes

2023-06-22 03:09 UTC, merged