ETC Ecosystem Spotlight: HebeSwap Part II
ethereumclassic/ethereumclassic.github.io pull request #1265
Opened 2023-06-21 04:27 UTC by DonaldMcIntyre

This is part two of two of the ETC Ecosystem Spotlight series about HebeSwap where we explain step-by-step how to buy HEBE with ETC, and how to transform ETC into WETC using the HebeSwap DEX.

"ETC Ecosystem Spotlight: HebeSwap Part II"

EN.

CN coming soon.

This one will be Published on July 4th of 2023.

2023-06-21 09:00 UTC, TheCrowbill requested changes

2023-06-21 09:00 UTC, TheCrowbill commented on content/blog/2023-07-04-etc-ecosystem-spotlight-hebeswap-part-ii/index.md
> +7. Once MetaMask opens, you will see your WETC balance. In our case, it is 2.34092, which is the amount of ETC we transformed to WETC.
Line 105: Remove comma
```suggestion
7. Once MetaMask opens you will see your WETC balance. In our case, it is 2.34092 which is the amount of ETC we transformed to WETC.
```

2023-06-22 21:19 UTC, TheCrowbill commented
Renamed for consistency with articles already merged to the website.

2023-07-04 05:53 UTC, brolal approved these changes

2023-07-05 05:06 UTC, merged