Etc course: 30. What Are File Storage Coins?
ethereumclassic/ethereumclassic.github.io pull request #1284
Opened 2023-07-01 03:37 UTC by DonaldMcIntyre

This is class 30 of the ETC course that explains file storage coins.

"Ethereum Classic Course: 30. What Are File Storage Coins?"

EN.

CN coming soon.

This one will be published on July 13th so we have a 13 day lead.

2023-07-12 08:22 UTC, TheCrowbill requested changes

2023-07-12 08:22 UTC, TheCrowbill commented on content/blog/2023-07-13-ethereum-classic-course-30-what-are-file-storage-coins/index.md
> +Storage providers must inform with a certain frequency to the peer-to-peer network of the integrity of the data they store as a proof of storage. Content users are the ones who use the network to sto
Line 63:  Revise for clarity
```suggestion
As proof of storage, storage providers must inform the peer-to-peer network of the integrity of the data they store on a regular basis. Users are the ones who store their data on the network. Retrieval providers are like brokers who get paid to communicate with users and retrieve popular content from storage providers for quicker delivery. 
```

2023-07-12 08:22 UTC, TheCrowbill commented on content/blog/2023-07-13-ethereum-classic-course-30-what-are-file-storage-coins/index.md
> +In essence Filecoin is like a marketplace where data storage around the world is put for sale and the protocol acts as the pricing and payment system where users compensate storage and retrieval prov
Line 65: Revise for clarity
```suggestion
In essence, Filecoin is a marketplace where data storage around the world is put up for sale and the protocol acts as the pricing and payment system where users compensate storage and retrieval providers for their content to be stored and delivered efficiently. 
```

2023-07-12 08:22 UTC, TheCrowbill commented on content/blog/2023-07-13-ethereum-classic-course-30-what-are-file-storage-coins/index.md
> +It is similar to Filecoin in that it is a content addressed network, and content units are broken up in chunks and stored in many peers in the system. BTT is the token that is used in this case.
Line 77: Revise for  clarity
```suggestion
It is similar to Filecoin in that it is a content-addressed network where content units are broken up into chunks and stored by many peers in the system. BTT is the token that is used in this case. 
```

2023-07-12 08:22 UTC, TheCrowbill commented on content/blog/2023-07-13-ethereum-classic-course-30-what-are-file-storage-coins/index.md
> +As we will see in the next 8 classes of the Ethereum Classic course, the blockchain industry will be divided in layers and many components will exist in each layer. These layers will be organized by
Line 106 Correct usage;
```suggestion
As we will see in the next 8 classes of the Ethereum Classic course, the blockchain industry will be divided into layers and many components will exist in each layer. These layers will be organized by security vs scalability degrees where the most secure but less scalable proof of work coins will constitute the base layer, and the rest of the more scalable but less secure systems, including proof of stake, will exist on top of the security layer.
```

2023-07-12 08:22 UTC, TheCrowbill commented on content/blog/2023-07-13-ethereum-classic-course-30-what-are-file-storage-coins/index.md
> +The file storage protocols side of these networks are just peer-to-peer file systems where the files are not actually stored in all the nodes, but just those who want to store them as they expect to
Line 131: Agreement
```suggestion
The file storage protocol side of these networks is just peer-to-peer file systems where the files are not actually stored in all the nodes, but just those who want to store them as they expect to get paid for serving them. 
```

2023-07-12 08:22 UTC, TheCrowbill commented on content/blog/2023-07-13-ethereum-classic-course-30-what-are-file-storage-coins/index.md
> +On the other hand, the decentralized ledgers that hold the accounts and balances of the file storage coins and conduct the payments for file storage providers are all proof of stake or proof of autho
Line 125: Spelling typo
```suggestion
On the other hand, the decentralized ledgers that hold the accounts and balances of the file storage coins and conduct the payments for file storage providers are all proof of stake or proof of authority systems. These are much less secure than proof of work networks.
```

2023-07-13 04:39 UTC, brolal approved these changes

2023-07-13 09:01 UTC, TheCrowbill approved these changes

2023-07-13 12:16 UTC, merged