How to Contribute to ETC: Operating a Node
ethereumclassic/ethereumclassic.github.io pull request #1291
Opened 2023-07-05 02:19 UTC by DonaldMcIntyre

This is part 6 of the series "How to Contribute to ETC". This is the one about the importance of operating a node.

"How to Contribute to ETC: Operating a Node"

EN.

CN coming soon.

This one will be published on July 18th, so we have a 14 day lead.

2023-07-17 11:48 UTC, TheCrowbill requested changes

2023-07-17 11:48 UTC, TheCrowbill commented on content/blog/2023-07-18-how-to-contribute-to-etc-operating-a-node/index.md
> +One way of operating a node is by download the Ethereum Classic software client, which is called Core-Geth.
Line 96: Rewrite for verb agreement, clarity, accuracy
```suggestion
One way of operating a node begins by downloading the Ethereum Classic client software called Core-Geth.
```

2023-07-17 19:20 UTC, TheCrowbill approved these changes

2023-07-18 03:48 UTC, brolal approved these changes

2023-07-18 11:56 UTC, merged