If It's Not Proof of Work, Then It's Not a Blockchain
ethereumclassic/ethereumclassic.github.io pull request #1297
Opened 2023-07-11 21:36 UTC by DonaldMcIntyre

This is an opinion post about what is a true blockchain, which must only be a proof of work network.

"If It's Not Proof of Work, Then It's Not a Blockchain"

EN.

CN coming soon.

This one will be published on July 25 2023.

2023-07-24 17:25 UTC, brolal submitted a review, later dismissed

2023-07-25 04:56 UTC, TheCrowbill requested changes

2023-07-25 12:46 UTC, DonaldMcIntyre commented
> Please don't merge this yet as I have some suggestions I want a bit of time to prepare properly.
> 
> I don't disagree with the notion of this article, but the developer in me feels there needs some clarification points about the technical definition of blockchain and it's common usage.
> 
> The idea that all non-PoW chains are not blockchains (without clarification), seems to be wrong technically, from a developer's point of view. For example, I think comparison could be made with a virtual blockchain (which is used for testing and development), which is still a "blockchain" on a technical level, but socially is not a "real" blockchain in the public ledger sense.
> 
> PoS is a type of virtual blockchain in this model, as it behaves like a blockchain and has similar data types, but is not a "real" blockchain.
> 
> It may also be also useful to bring in https://en.wikipedia.org/wiki/Hash_chain, to help understand definitions, which states.
> 
> > A hash chain is similar to a [blockchain](https://en.wikipedia.org/wiki/Blockchain), as they both utilize a [cryptographic hash function](https://en.wikipedia.org/wiki/Cryptographic_hash_function) for creating a link between two nodes. However, a blockchain (as used by [Bitcoin](https://en.wikipedia.org/wiki/Bitcoin) and related systems) is generally intended to support distributed agreement around a public ledger (data), and incorporates a set of rules for encapsulation of data and associated data permissions.
> 
> As well as BFT, https://en.wikipedia.org/wiki/Byzantine_fault, https://medium.com/@ianbondw/proof-of-work-vs-proof-of-stake-vs-other-byzantine-fault-tolerances-ff01f5de951
> 
> This is an argument in favor of this article as it suggests that the "public ledger" element is essential; being a "public ledger" is what makes a blockchain a blockchain, and PoS fails this test.
> 
> I think that we can keep developers and non-developer readers more amenable to the premise of the article by making these clarifications.

Thank you for the suggestions. I am arbitrarily making up the concept of block as a group of records that is hashed doing a lot of work as contrasted with one that is hashed with no work. The one with no work, including hash-chains, can be easily re-hashed with no effort, the one with work needs to do all the work again to re-hash it. Both are batches of data, just that I personally made up the idea that we can call "blocks" the one that were hashed with extra work. 

Satoshi never did this distinction, even if in the paper he mentions "block" or "blocks" 67 times. He only mentioned the timestamp concept. 

I marked this as an opinion, under the "philosophy" tag because it is just my opinion. Although, as usual, I present it as unavoidable truth!

2023-07-25 12:49 UTC, DonaldMcIntyre commented
> I decided not to suggest significant edits to these articles, they are Donald's to post.

Your suggestions are welcome! 

This is the key paragraph that defines the "block" as in my conception in the article:

> In computer science, a group of data, or selection of records from a set of data, is called a "batch". When a batch of Ethereum Classic (ETC) transactions, a proof of work blockchain, is grouped and then is sealed with a proof of work stamp or hash, then it is called a "block". If it is not sealed, then it remains just an unprotected batch of data.

2023-07-25 20:26 UTC, TheCrowbill approved these changes

2023-07-25 20:36 UTC, merged