News Update
ethereumclassic/ethereumclassic.github.io pull request #588
Opened 2020-10-09 17:33 UTC by TheEnthusiasticAs

2020-10-09 17:34 UTC, gitr0n1n approved these changes

2020-10-09 19:50 UTC, developerkevin requested changes
Please remove Besu to implement MESS as Chainsafe is no longer doing so. 

Also change, "_There was a consensus for the Ethereum Classic...._" at the start of the sentence to "*Consensus has been gathered regarding the Ethereum Classic Best Practice"

2020-10-09 20:16 UTC, TheEnthusiasticAs commented
done @developerkevin

2020-10-12 03:16 UTC, developerkevin commented
Thanks. LGTM.

2020-10-12 03:22 UTC, developerkevin approved these changes

2020-10-12 05:31 UTC, merged