News Updates
ethereumclassic/ethereumclassic.github.io pull request #614
Opened 2020-12-04 19:38 UTC by TheEnthusiasticAs

2020-12-04 23:29 UTC, gitr0n1n approved these changes
LGTM, sorry for messing with the articles.

2020-12-04 23:30 UTC, gitr0n1n requested changes
Something in your formatting is broken. @TheEnthusiasticAs

2020-12-05 08:16 UTC, TheEnthusiasticAs commented
> Something in your formatting is broken. @TheEnthusiasticAs

corrected. Thx! Don't worry. Can happen with the mess ;)

2020-12-05 15:03 UTC, gitr0n1n approved these changes

2020-12-06 17:37 UTC, kimisan approved these changes

2020-12-06 19:45 UTC, merged