Updates
ethereumclassic/ethereumclassic.github.io pull request #662
Opened 2021-09-12 07:41 UTC by TheEnthusiasticAs

2021-09-12 11:26 UTC, w1g0 commented
Can you add that the Mantis Client isn't fully operational to avoid questions why people can't sync with Magneto?

2021-09-13 19:14 UTC, TheEnthusiasticAs commented
@w1g0 thx for the comments. I updated the PRs

2021-09-13 19:15 UTC, w1g0 approved these changes

2021-09-13 20:29 UTC, developerkevin requested changes
as far as placing mantis on the list of clients, I think we should either hold off on that until its live on ETC mainnet or add the word BETA next to it, and make sure to make it apparent that it is not mainnet ready until Magneto opcodes implemented but even then there may be other upgrades to add right after i.e. Keccak, FlyClients or NiPoPoWs, Account Versioning, others.

2021-09-13 22:36 UTC, w1g0 commented on content/development/clients/clients.en.yaml
> +    description: Mantis will be a fully featured client and wallet UI, developed from the ground up and written in Scala for the Ethereum Classic network (ETC). Created by IOHK to add robustness and
Stating explicitly in the in the name that Mantis is not main net ready/Beta version is a good idea. If people want to configure the client to sync with Sagano they should be able to with the provided link.

2021-09-22 09:03 UTC, hitchcott approved these changes

2021-09-22 09:08 UTC, hitchcott commented on content/development/clients/clients.en.yaml
> +    description: Mantis will be a fully featured client and wallet UI, developed from the ground up and written in Scala for the Ethereum Classic network (ETC). Created by IOHK to add robustness and
I added those changes

2021-09-22 09:11 UTC, hitchcott approved these changes

2021-09-22 10:06 UTC, developerkevin approved these changes
LGTM

2021-09-22 10:06 UTC, merged